name: Peer Discovery AWS Integration Test
on:
  push:
    paths:
      - 'deps/rabbitmq_peer_discovery_aws/**'
jobs:
  peer-discovery-aws-integration-test:
    name: Integration Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        erlang_version:
        - "23"
    timeout-minutes: 45
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2.3.4
    - name: WAIT FOR OCI IMAGE WORKFLOW
      uses: lewagon/wait-on-check-action@v0.2
      with:
        ref: ${{ github.ref }}
        check-name: build-publish-dev
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30 # seconds
    - name: CONFIGURE BAZEL
      run: |
        echo "${{ secrets.BUILDBUDDY_CERT }}" > buildbuddy-cert.pem
        echo "${{ secrets.BUILDBUDDY_KEY }}" > buildbuddy-key.pem
        cat << EOF >> .bazelrc
          build --remote_executor=grpcs://cloud.buildbuddy.io
          build --host_platform=//:erlang_${{ matrix.erlang_version }}_platform
          build --platforms=//:erlang_${{ matrix.erlang_version }}_platform
          build --extra_execution_platforms=//:erlang_${{ matrix.erlang_version }}_platform

          build --crosstool_top=@buildbuddy_toolchain//:toolchain
          build --extra_toolchains=@buildbuddy_toolchain//:cc_toolchain
          build --javabase=@buildbuddy_toolchain//:javabase_jdk8
          build --host_javabase=@buildbuddy_toolchain//:javabase_jdk8
          build --java_toolchain=@buildbuddy_toolchain//:toolchain_jdk8
          build --host_java_toolchain=@buildbuddy_toolchain//:toolchain_jdk8

          build --@bazel-erlang//:erlang_version=${{ matrix.erlang_version }}
          build --@bazel-erlang//:erlang_home=/usr/lib/erlang
          build --//:elixir_home=/usr/local

          build --bes_results_url=https://app.buildbuddy.io/invocation/
          build --bes_backend=grpcs://cloud.buildbuddy.io
          build --remote_cache=grpcs://cloud.buildbuddy.io
          build --tls_client_certificate=buildbuddy-cert.pem
          build --tls_client_key=buildbuddy-key.pem
          build --remote_timeout=1200

          build --build_metadata=ROLE=CI
          build --build_metadata=VISIBILITY=PRIVATE
          build --remote_instance_name=buildbuddy-io/buildbuddy/ci-aws
          build --grpc_keepalive_time=30s
        EOF
    #! - name: Setup tmate session
    #!   uses: mxschmitt/action-tmate@v3
    - name: RUN INTEGRATION TESTS
      run: |
        bazelisk test //deps/rabbitmq_peer_discovery_aws:integration_SUITE \
          --test_tag_filters=aws \
          --build_tests_only \
          --test_env AWS_ACCESS_KEY_ID=${{ secrets.CONCOURSE_AWS_ACCESS_KEY_ID }} \
          --test_env AWS_SECRET_ACCESS_KEY=${{ secrets.CONCOURSE_AWS_SECRET_ACCESS_KEY }} \
          --test_env RABBITMQ_IMAGE="pivotalrabbitmq/rabbitmq:${GITHUB_REF##*/}" \
          --verbose_failures
